# Generated by Django 4.0.2 on 2022-02-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDatabaseTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_identifier", models.CharField(max_length=255, unique=True)),
                ("database_name", models.CharField(max_length=255)),
            ],
        ),
    ]
